import Head from 'next/head';
import { FC } from 'react';
import styles from '../../styles/MainLayout.module.css'
import { Navbar } from '../Navbar';


export const MainLayout: FC = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home - Jo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar></Navbar>
            <main className={styles.main}>
                {children}
            </main>
        </div>
    );
}